[tool.poetry]
name = "Digital-desire"
version = "0.1.0"
description = ""
authors = ["Digital-desire"]

[tool.poetry.dependencies]
python = "3.9.7"
sphinx = "4.1.2"
sphinxcontrib-needs = "*"
sphinx-rtd-theme = "*"
Django = "^3.2.7"

[tool.poetry.dev-dependencies]
