[tool.poetry]
name = "pozabanka technical documentation"
version = "0.1.0"
description = ""
authors = ["pozabanka team"]

[tool.poetry.dependencies]
python = "3.9.*"
sphinx = "4.1.2"
sphinxcontrib-needs = "0.7.2"
sphinx-rtd-theme = "1.0.0"
sphinx-autobuild = "2021.3.14"
